### ISSUE TITLE
[App] Can't Withdraw LCAD

### ISSUE THREAD

**Issue by sinqinc** [tdex-network/support#1]
Hi,

I'm trying to figure out why I can't withdraw L-CAD funds to BullBitcoin. I'm getting "Error 12: An error occurs while sending withdraw transaction".

Could be nice to add error code definition in your FAQ.

Thank you

**Comment by tiero** [comment]
Hello @sinqinc. Do you have enough L-BTC to pay for transaction fees? ie. 400-500 satoshis of L-BTC to be sure

**Comment by sinqinc** [comment]
> Hello @sinqinc. Do you have enough L-BTC to pay for transaction fees? ie. 400-500 satoshis of L-BTC to be sure

Do I need to leave the fee in L-BTC before the L-CAD Withdrawal ? I think I have enough fee in L-CAD.

**Comment by tiero** [comment]
> > Hello @sinqinc. Do you have enough L-BTC to pay for transaction fees? ie. 400-500 satoshis of L-BTC to be sure
> 
> Do I need to leave the fee in L-BTC before the L-CAD Withdrawal ? I think I have enough fee in L-CAD.

Yes, any Liquid transactions needs a bit of that to transact. You can sell something like 10 cents worth of LCAD via the Exchange tab so you can withdraw funds.

**Comment by sinqinc** [comment]
I swaped 0.66 LCAD to L-BTC 1379sats and I have the same error.

**Comment by sinqinc** [comment]
Ok problem solved, I copy/pasted the address instead of using the QR code.

EDIT : The QR code resolved to a liquidnetwork://XXXXXXXX URL instead of just the address.

**Comment by tiero** [comment]
> EDIT : The QR code resolved to a liquidnetwork://XXXXXXXX URL instead of just the address.

Is it that shown by BullBitcoin right? it looks like we dont support payment URL

**Comment by sinqinc** [comment]
> > EDIT : The QR code resolved to a liquidnetwork://XXXXXXXX URL instead of just the address.
> 
> Is it that shown by BullBitcoin right? it looks like we dont support payment URL

yes it is.
